#!/bin/sh

case $1 in
  build)
    trellis --output-dir . healthy.trellis > /dev/null
    ;;
  run)
    python3 runner.py
    ;;
  clean)
    rm -rf *generated* viterbi.py __init__.py __pycache__
    ;;
  *)
    >&2 echo "Expected argument 'build', 'run' or 'clean'"
    exit 1
    ;;
esac
