name: trellis-bench
channels:
  - nvidia/label/cuda-11.7.0
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - six
  - matplotlib
  - h5py
  - cuda-toolkit
  - cuda-version=11.7
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - mkl=2024.0.0
  - numpy<2.0
  - hyperfine
  - pip:
    - pomegranate==1.0.4
    - levenshtein
